# Generated by Django 4.0.3 on 2022-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDataset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('label', models.TextField()),
                ('split', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
